<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Blobs\Events\BlobEvents.csZone.Identifier" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../libraries/MicroKit.Domain/MicroKit.Domain.csproj" />
    <ProjectReference Include="../../libraries/MicroKit.Persistence/src/MicroKit.Persistence.Abstractions/MicroKit.Persistence.Abstractions.csproj" />
  </ItemGroup>

</Project>
