namespace Ged.Api.Composition;

/// <summary>Response headers that cost nothing and close whole classes of attack.</summary>
internal static class SecurityHeaders
{
    /// <summary>The path the interactive API reference is served from.</summary>
    /// <remarks>
    /// Shared with the mapping so the policy and the route cannot drift apart. Moving the reference
    /// without moving this constant would silently apply the API policy to an HTML page, and the
    /// page would render blank.
    /// </remarks>
    public const string DocsPathPrefix = "/scalar";

    // An API returns data, never markup. Forbidding every source means a response that somehow
    // reaches a browser as a document can still execute nothing.
    private const string ApiPolicy =
        "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'";

    // The reference IS a document, and it is the one place in this application that legitimately
    // ships scripts and styles. Everything is still restricted to this origin — the only relaxation
    // is 'unsafe-inline', which the UI needs for the configuration block it injects into the page.
    //
    // Acceptable here for a reason that does not generalise: the page is static, generated by the
    // application, and contains no user-supplied content. There is nothing on it for an injected
    // script to have come from. Do not copy this policy onto a page that renders anything a user
    // sent.
    private const string DocsPolicy =
        "default-src 'none'; "
        + "script-src 'self' 'unsafe-inline'; "
        + "style-src 'self' 'unsafe-inline'; "
        + "img-src 'self' data:; "
        + "font-src 'self' data:; "
        + "connect-src 'self'; "
        + "frame-ancestors 'none'; "
        + "base-uri 'none'; "
        + "form-action 'none'";

    /// <summary>Adds the response headers.</summary>
    /// <param name="app">The application.</param>
    /// <returns>The same application, for chaining.</returns>
    public static WebApplication UseGedSecurityHeaders(this WebApplication app)
    {
        ArgumentNullException.ThrowIfNull(app);

        app.Use(async (context, next) =>
        {
            var headers = context.Response.Headers;

            // Stops a browser from re-interpreting a JSON response as HTML or script — the vector
            // that turns a stored filename into a cross-site scripting payload.
            headers["X-Content-Type-Options"] = "nosniff";
            headers["X-Frame-Options"] = "DENY";
            headers["Referrer-Policy"] = "no-referrer";

            var isDocs = context.Request.Path.StartsWithSegments(
                DocsPathPrefix, StringComparison.OrdinalIgnoreCase);

            headers["Content-Security-Policy"] = isDocs ? DocsPolicy : ApiPolicy;

            if (!isDocs)
            {
                headers["Cross-Origin-Resource-Policy"] = "same-origin";
            }

            await next();
        });

        return app;
    }
}
