<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Ged.Migrations</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="dbup-sqlserver" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts/**/*.sql" />
  </ItemGroup>

</Project>
